ECHO_TEST: FW_config.yaml is loaded for d3tales, this file is (presumbly) located at d3tales/high_throughput/config/FW_config.yaml

#ADD_USER_PACKAGES:
#  -workflows.python

LAUNCHPAD_LOC: BASE_PATH/config/my_launchpad.yaml

FWORKER_LOC: BASE_PATH/config/my_fireworker.yaml

#_launch_dir: /pscratch/cmri235_uksr/d3tales/fw/dev/d3tales_fw/launch

# set to FIFO if you want older FireWorks to be run first, FILO if you want recent FireWorks run first.
# Note that higher priority FireWorks are always run first.
SORT_FWS: 'FIFO'

# whether to print the FW.json file in your run directory
PRINT_FW_JSON: True

# whether to print the FW.yaml file in your run directory
PRINT_FW_YAML: False

# the name to give the script for submitting PBS/SLURM/etc. queue jobs
SUBMIT_SCRIPT_NAME: FW_submit.sh

# format for loggers (this String will be passed to logging.Formatter())
FW_LOGGING_FORMAT: "%(asctime)s %(levelname)s %(message)s"

# set True if you want the Queue Launcher to always create a new block directory every time it is called,
# False if you want to re-use previous blocks
ALWAYS_CREATE_NEW_BLOCK: False

# where to store templates if you are using the TemplateWriterTask.
# TEMPLATE_DIR:

# tries to delete empty launch directories created when setting the _launch_dir in the spec of your Firework.
REMOVE_USELESS_DIRS: True

# if True, when rerunning a FIZZLED Firework, the serialized exception details are added to the spec.
EXCEPT_DETAILS_ON_RERUN: True

# the default host on which to run the web server
WEBSERVER_HOST: 127.0.0.1

# the default port on which to run the web server
WEBSERVER_PORT: 5000
#
# the max length of the job name to send to the queuing system (some queuing systems limit the size of job names)
QUEUE_JOBNAME_MAXLEN: 20

